project:
  type: book
  output-dir: docs
lang: pt


book:
  title: "Notas de Aula \n Análise de Sobrevivência"
  author: "Alisson Rosa"
  date: ""
  chapters:
    - index.qmd
    - intro.qmd
    - def.qmd
    - prog.qmd
    - summary.qmd
    - references.qmd
  favicon: "clock.png"
  navbar:
    search: true
    location: navbar
    type: overlay
    right:
      - icon: github
        href: https://github.com/AlissonRP/survival_analysis
        

bibliography: references.bib  

format:
  html:
    theme: litera
  pdf:
    documentclass: scrreprt



