project:
  type: book
  output-dir: docs
lang: pt
nocite: '@*'


book:
  title: "Notas de Aula \n Análise de Sobrevivência"
  author: "Alisson Rosa"
  date: ""
  chapters:
    - index.qmd
    - part: "Introdução"
      chapters:
      - caps/intro.qmd
    - part: "Conceitos Básicos"
      chapters:
      - caps/def.qmd
      - caps/prog.qmd
    - part: "Análise Não paramétrica"
      chapters:
      - caps/eda.qmd
    - caps/summary.qmd
    - part: "Análise Paramétrica"
      chapters:
      - caps/parametric.qmd
    - part: "Modelagem"
      chapters:
      - caps/models.qmd
  appendices:
    - caps/apend.qmd
    - references.qmd
  favicon: "favicon"
  navbar:
    search: true
    location: navbar
    type: overlay
    right:
      - icon: github
        href: https://github.com/AlissonRP/survival_analysis
        

bibliography: references.bib  

format:
  html:
    theme: litera
  pdf:
    documentclass: scrreprt



